services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    environment:
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - PLAYWRIGHT_HTML_PORT=9323
      - CI=${CI}
    ports:
      - 0.0.0.0:9323:9323
    volumes:
      - ${PWD}:/app
    command: npx playwright test